### ISSUE TITLE
crash when opening an application's crashlog

### ISSUE THREAD

**Issue by theotheroracle** [TacoTheDank/Scoop#70] opened 2022-11-08 03:06 UTC
```
type: crash
osVersion: OnePlus/OnePlus7T/OnePlus7T:12/SQ3A.220705.004/eng.emy.20221009.051326:user/release-keys
package: taco.scoop:34
process: taco.scoop

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1060928 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:87)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
Caused by: android.os.TransactionTooLargeException: data parcel size 1060928 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:571)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1315)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:84)
	... 9 more

```

**Comment by TacoTheDank** [comment] 2022-11-08 15:09
Duplicate of #45.

This can be fixed temporarily by cleaning up old crashes.

**Closed by TacoTheDank** 2022-11-08 15:09 UTC
