### ISSUE TITLE
The app crashed when I pressed any button. I deleted 512 error data in one app and it stopped crashing (android 12, miui 13.0.5, api 31).

### ISSUE THREAD

**Issue by Wjxfi** [TacoTheDank/Scoop#68] opened 2022-10-23 21:06 UTC
FATAL EXCEPTION: main
Process: taco.scoop, PID: 30645
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1786452 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: android.os.TransactionTooLargeException: data parcel size 1786452 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:624)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1297)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
	... 9 more

**Comment by TacoTheDank** [comment] 2022-10-25 04:27
Duplicate of #45.

**Closed by TacoTheDank** 2022-10-25 04:27 UTC
