### ISSUE TITLE
Crashes when opening settings

### ISSUE THREAD

**Issue by dgudim** [TacoTheDank/Scoop#78] opened 2023-07-19 05:26 UTC
Fortunately It captured its own stacktrace
After clearing the crash log it opened again.

```
FATAL EXCEPTION: main
Process: taco.scoop, PID: 26994
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2170956 bytes
	at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8757)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: android.os.TransactionTooLargeException: data parcel size 2170956 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:662)
	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1309)
	at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
	... 9 more
```

**Comment by TacoTheDank** [comment] 2023-07-20 21:28
Duplicate of #45

**Closed by TacoTheDank** 2023-07-20 21:28 UTC
