### ISSUE TITLE
Start automatically at boot

### ISSUE THREAD

**Issue by Kreuger** [TacoTheDank/Scoop#19] opened 2021-07-06 13:36 UTC
Hey man. I noticed that the app doesnt start automatically after restarting my phone and I often forget to do it. Could you add this in as an option?

**Comment by TacoTheDank** [comment] 2021-07-06 16:22
Yes, I will attempt to tackle this :) Also, duplicate of https://github.com/TacoTheDank/Scoop/issues/4

**Closed by TacoTheDank** 2021-07-06 16:22 UTC
Labels: duplicate

**Comment by TacoTheDank** [comment] 2021-07-13 00:24
🦀 It is crab-rave time 🦀 https://github.com/TacoTheDank/Scoop/pull/20
